# PART1

In [2]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

with open('data_1.txt', 'r') as f:
    data = f.readlines()

column_name = data[0].strip().split()

print(column_name)

data_split = [x.strip().split() for x in data[1:]]

print(data_split[0])

['Price', 'Age_08_04', 'KM', 'HP', 'Met_Color', 'Automatic', 'CC', 'Doors', 'Quarterly_Tax', 'Weight', 'Fuel_Type_CNG', 'Fuel_Type_Diesel', 'Fuel_Type_Petrol', 'Fuel_Type']
['13500', '23', '46986', '90', '1', '0', '2000', '3', '210', '1165', '0', '1', '0', 'Diesel']

In [3]:
df = pd.DataFrame(data_split, columns = column_name)

df

,Price,Age_08_04,KM,HP,Met_Color,Automatic,CC,Doors,Quarterly_Tax,Weight,Fuel_Type_CNG,Fuel_Type_Diesel,Fuel_Type_Petrol,Fuel_Type
0,13500,23,46986,90,1,0,2000,3,210,1165,0,1,0,Diesel
1,13750,23,72937,90,1,0,2000,3,210,1165,0,1,0,Diesel
2,13950,24,41711,90,1,0,2000,3,210,1165,0,1,0,Diesel
3,14950,26,48000,90,0,0,2000,3,210,1165,0,1,0,Diesel
4,13750,30,38500,90,0,0,2000,3,210,1170,0,1,0,Diesel
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1431,7500,69,20544,86,1,0,1300,3,69,1025,0,0,1,Petrol
1432,10845,72,19000,86,0,0,1300,3,69,1015,0,0,1,Petrol
1433,8500,71,17016,86,0,0,1300,3,69,1015,0,0,1,Petrol
1434,7250,70,16916,86,1,0,1300,3,69,1015,0,0,1,Petrol
1435,6950,76,1,110,0,0,1600,5,19,1114,0,0,1,Petrol

In [5]:
X = df[['KM', 'CC', 'HP']]
y = df['Price']

model = LinearRegression()

bootstraps = 2000

preds = np.zeros(bootstraps)
means = np.zeros(bootstraps)
stds = np.zeros(bootstraps)

for i in range(bootstraps):
    sample_indices = np.random.choice(X.shape[0], size=X.shape[0], replace=True)
    X_sample = X.iloc[sample_indices]
    y_sample = y.iloc[sample_indices]
    
    model.fit(X_sample, y_sample)
    preds[i] = model.predict(X.iloc[0:1])[0]
    
    means[i] = preds[0:i+1].mean()
    stds[i] = preds[0:i+1].std()

exp_pred = means.mean()
std_pred = stds.mean()

# Print the results
print('Expectation of the predicted value:', exp_pred)
print('Standard deviation of the predicted value:', std_pred)

Expectation of the predicted value: 12979.110814215295
Standard deviation of the predicted value: 1339.2799851914504

# PART2

In [17]:
def mape(y_true,y_pred):
    return np.mean(np.abs(y_true-y_pred)/y_true) * 100

# PART3
cross-validation의 원리를 이용해서 order를 변경해가면서 가장 좋은 성능을 내는 order를 선택할 것 같다.

# PART4

1. 더 많은 데이터를 수집한다.
2. cross-validation을 통해 모델을 여러 번 학습시킨다.
3. Scaler를 통해 데이터를 정규화, 표준화한다.