In [1]:
import pandas as pd

In [2]:
#from google.colab import drive
#drive.mount("/content/drive/")


#myfilename = "/content/drive/MyDrive/Colab Notebooks/MLDM/wineTraining.csv"
#WineData = pd.read_csv(myfilename)
WineData = pd.read_csv('wineTraining.csv')

WineData.head(n=6)
#WineDataQuality = WineData[0:WineData.shape[0]][0:1]
#WineDataQuality = WineData[0:][0:1]
WineDataQuality = WineData['Wine']
print(WineDataQuality)
#WineInput = WineData.loc[:, WineData.columns != 'Wine']


#WineInput : X
#table에서 열의 차례대로 X1,X2,X3...
#w:XTX의 eigenvector(loading vector)
WineInput = WineData.loc[:, ~WineData.columns.isin(['Wine'])]
WineInput

0      1
1      1
2      1
3      1
4      1
      ..
171    3
172    3
173    3
174    3
175    3
Name: Wine, Length: 176, dtype: int64

,Alcohol,Malic.acid,Ash,Acl,Mg,Phenols,Flavanoids,Nonflavanoid.phenols,Proanth,Color.int,Hue,OD,Proline
0,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
...,...,...,...,...,...,...,...,...,...,...,...,...,...
171,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740
172,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750
173,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835
174,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840
175,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560

In [3]:
WineData

,Wine,Alcohol,Malic.acid,Ash,Acl,Mg,Phenols,Flavanoids,Nonflavanoid.phenols,Proanth,Color.int,Hue,OD,Proline
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
171,3,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740
172,3,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750
173,3,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835
174,3,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840
175,3,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560

In [4]:
import numpy as np

In [5]:
#https://www.datacamp.com/community/tutorials/principal-component-analysis-in-python
from sklearn.preprocessing import StandardScaler
x = WineInput.values
#x = StandardScaler().fit_transform(x) # normalizing the features
stdscalar = StandardScaler()
stdscalar.fit(x)
x = stdscalar.transform(x)
#print( np.mean(x),"    ", np.std(x) )
#print(pd.DataFrame(WineInput.values).head())
print(pd.DataFrame(x).head())

#print( stdscalar.transform(WineInput.values[0:1]) - x[0:1,])
#print( x[0:1,])

         0         1         2         3         4         5         6   \
0  1.517774 -0.559685  0.233940 -1.167670  1.910743  0.820184  1.044971
1  0.244734 -0.496530 -0.820855 -2.486193  0.013574  0.578980  0.743092
2  0.195296  0.026759  1.106873 -0.268676  0.083840  0.820184  1.226098
3  1.690809 -0.343152  0.488545 -0.808072  0.927026  2.508610  1.477664
4  0.294173  0.234270  1.834317  0.450518  1.278353  0.820184  0.672653

         7         8         9         10        11        12
0 -0.665037  1.222788  0.249743  0.354946  1.839946  1.023298
1 -0.826258 -0.540805 -0.294829  0.398650  1.109332  0.975364
2 -0.503816  2.130777  0.267031  0.311242  0.786176  1.406776
3 -0.987479  1.030714  1.183296 -0.431726  1.179584  2.349493
4  0.221679  0.402106 -0.320761  0.354946  0.448970 -0.031267

In [6]:
feat_cols = ['feature'+str(i) for i in range(x.shape[1])]
normalised_WineInput = pd.DataFrame(x,columns=feat_cols)
normalised_WineInput.head()

,feature0,feature1,feature2,feature3,feature4,feature5,feature6,feature7,feature8,feature9,feature10,feature11,feature12
0,1.517774,-0.559685,0.233940,-1.167670,1.910743,0.820184,1.044971,-0.665037,1.222788,0.249743,0.354946,1.839946,1.023298
1,0.244734,-0.496530,-0.820855,-2.486193,0.013574,0.578980,0.743092,-0.826258,-0.540805,-0.294829,0.398650,1.109332,0.975364
2,0.195296,0.026759,1.106873,-0.268676,0.083840,0.820184,1.226098,-0.503816,2.130777,0.267031,0.311242,0.786176,1.406776
3,1.690809,-0.343152,0.488545,-0.808072,0.927026,2.508610,1.477664,-0.987479,1.030714,1.183296,-0.431726,1.179584,2.349493
4,0.294173,0.234270,1.834317,0.450518,1.278353,0.820184,0.672653,0.221679,0.402106,-0.320761,0.354946,0.448970,-0.031267

In [15]:
from sklearn.decomposition import PCA
pca_wine = PCA(n_components=2)
#principalComponents_Wine = pca_wine.fit_transform(x)
#loading vector가 pca_wine에 저장됨
print(pca_wine.fit(x))
pca_wine.components_[0]

#scoring vector를 뽑아냄 (principal component)
principalComponents_Wine = pca_wine.transform(x)

principal_wine_Df = pd.DataFrame(data = principalComponents_Wine
             , columns = ['principal component 1', 'principal component 2'])
#print(principal_wine_Df.tail(n=8))
principal_wine_Df

#print(pca_wine.explained_variance_ratio_)

PCA(n_components=2)

array([ 0.13657084, -0.24486357, -0.00580443, -0.23706005,  0.13650382,
        0.39456991,  0.42390616, -0.2969257 ,  0.31305697, -0.09979776,
        0.30215397,  0.38011604,  0.2814775 ])

### loading vector = weight vector
eigenvector 에다가 eigenvalue의 제곱근 곱한 것.
weight vector라고 합이 같은 것은 아님.

In [ ]:
vector1=np.transpose(principal_wine_Df['principal component 1'])
vector2=principal_wine_Df['principal component 2']
np.dot(vector1,vector2)

In [ ]:
#WineDataQuality
#print( np.unique (WineDataQuality) )

#stdscalar2.transform(WineInput.values[0:1])

#print( pca_wine.fit_transform(x,stdscalar2.transform(WineInput.values[0:1]) ) )
#WineDataQuality[WineDataQuality == 1]
#print(stdscalar2.transform(WineInput.values[0:1]))
print( pca_wine.transform( stdscalar.transform(WineInput.values[0:2]) )) 
print(principalComponents_Wine[0:2])
#print(principalComponents_Wine[0:2,1])
#print( principalComponents_Wine.shape )

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
plt.figure()
plt.figure(figsize=(10,10))
plt.xticks(fontsize=12)
plt.yticks(fontsize=14)
plt.xlabel('Principal Component - 1',fontsize=20)
plt.ylabel('Principal Component - 2',fontsize=20)
plt.title("Principal Component Analysis of Wine Dataset",fontsize=20)
targets = list(np.unique (WineDataQuality))
print(targets)

colors = ['r', 'g', 'b']
for target, color in zip(targets, colors):
    indicesToKeep = (WineDataQuality == target)
    plt.scatter(principal_wine_Df.loc[indicesToKeep, 'principal component 1']
               , principal_wine_Df.loc[indicesToKeep, 'principal component 2'], c = color, s = 50)

plt.legend(targets,prop={'size': 15})

In [ ]:
from sklearn.cluster import KMeans

In [ ]:
kmeans = KMeans(n_clusters=3).fit(principal_wine_Df)
groups = np.unique ( kmeans.labels_)
for group, color in zip(groups, colors):
    indicesToKeep = (kmeans.labels_ == group)
    plt.scatter(principal_wine_Df.loc[indicesToKeep, 'principal component 1']
               , principal_wine_Df.loc[indicesToKeep, 'principal component 2'], c = color, s = 50)

plt.legend(targets,prop={'size': 15})

#plt.scatter(kmeans.cluster_centers_[:, 0], kmeans.cluster_centers_[:, 1], s = 200, c = 'yellow', label = 'Centroids')

#for i, l in enumerate(kmeans.labels_):
#    plt.plot(principal_wine_Df[i], principal_wine_Df[i], color=colors[l], marker=markers[l])

In [ ]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(WineDataQuality, kmeans.labels_))


pred_label = kmeans.labels_.copy()
#pred_label[kmeans.labels_ == 1] = 1
pred_label[kmeans.labels_ == 0] = 3
#pred_label[kmeans.labels_ == 2] = 3
print( confusion_matrix(WineDataQuality, pred_label) )

In [ ]:
#myfilename = "/content/drive/MyDrive/Colab Notebooks/MLDM/wineTesting.csv"
#WineTestData = pd.read_csv(myfilename)
WineTestData = pd.read_csv('wineTesting.csv')
#2x13
print(WineTestData)

WineTestDataQuality = WineTestData['Wine']
#WineInput = WineData.loc[:, WineData.columns != 'Wine']
WineTestInput = WineTestData.loc[:, ~WineTestData.columns.isin(['Wine'])]
print(WineTestInput)

In [ ]:
newPCAscores = pca_wine.transform( stdscalar.transform(WineTestInput) )
print(newPCAscores )

test sample 의 PCA는 서로 수직이 아니다. weight vector 가 train set에 있던 걸 사용했기 때문인듯.

In [ ]:
plt.figure()
plt.figure(figsize=(10,10))
plt.xticks(fontsize=12)
plt.yticks(fontsize=14)
plt.xlabel('Principal Component - 1',fontsize=20)
plt.ylabel('Principal Component - 2',fontsize=20)
plt.title("Principal Component Analysis of Wine Dataset",fontsize=20)
targets = list(np.unique (WineDataQuality))
colors = ['r', 'g', 'b']
for target, color in zip(targets, colors):
    indicesToKeep = (WineDataQuality == target)
    plt.scatter(principal_wine_Df.loc[indicesToKeep, 'principal component 1']
               , principal_wine_Df.loc[indicesToKeep, 'principal component 2'], c = color, s = 50)

plt.legend(targets,prop={'size': 15})

plt.scatter(newPCAscores[0,0], newPCAscores[0,1], marker='>', c='y', s=300 )
plt.scatter(newPCAscores[1,0], newPCAscores[1,1], marker='<', c='b', s=300 )